M48
; DRILL file {KiCad 8.0.0} date 2024-03-25T15:19:05-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-25T15:19:05-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0374
%
G90
G05
T1
X5.7888Y-2.5758
X6.0163Y-2.5758
T2
X4.248Y-2.3819
X4.3661Y-2.3819
T3
X7.7802Y-3.6604
X7.7802Y-3.9281
M30
