M48
; DRILL file {KiCad 8.0.0} date 2024-04-04T13:49:09-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-04T13:49:09-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.000
%
G90
G05
T1
X147.035Y-65.425
X152.815Y-65.425
T2
X131.0Y-60.5
X134.0Y-60.5
T3
X197.431Y-93.158
X197.431Y-101.134
M30
